### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ChHecker** [lgrcia/twirl#27]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/lgrcia/twirl/issues?q=is%3Aissue).

## Question

The README contains an image saying this repository is licensed under the MIT license, but there is no LICENSE file. I am not sure whether it is legally required, so to be on the save side, could you confirm that this is the case?

**Comment by michealroberts** [comment]
Hi @ChHecker We will add the corresponding LICENSE file to the repository shortly.

I can confirm that this project adheres to the MIT license, and is free and open-source to use for your research.

**Comment by ChHecker** [comment]
Thanks for your swift response! That's great to hear!

**Comment by michealroberts** [comment]
No worries, thanks @ChHecker
